service: hashtab-api

custom:
  serverless-offline:
    port: 3000

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}
  region: us-west-2

plugins:
  - serverless-offline

functions:
  server:
    handler: src/server.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
